#
# Makefile for TI's shared transport line discipline
# and its protocol drivers (BT, FM, GPS)
#
//德州仪器的串口的线路规程，为蓝牙 收音机 GPS 共用的
obj-$(CONFIG_TI_ST) 		+= st_drv.o
st_drv-objs			:= st_core.o st_kim.o st_ll.o
